### ISSUE TITLE
PhotoSwipe not loading

### ISSUE THREAD

**Issue by saaage** [Sage911/gallery-practice#1]
index.js not loading photoswipe when _init() is called. Says that 'onclick' is pointed to null instead of photoswipe button :(

**Comment by jasonvanderslice** [comment]
1. Create new file to store your "Photo Gallery"
    - Only use `index.js` to press "start" on your "Photo Gallery"
2. Inside of this new file wait for the `DOMContentLoaded` event to fire to call init on PhotoGallery
3. Rename your spec file to reflect this new "PhotoGallery" testing
